%%metro title: Tumour/normal WES
%%metro diamond_style: symmetric
%%metro style: dark
%%metro legend: bl
%%metro files: pairs_in | CRAM | T/N pairs
%%metro files: somatic_out | VCF | Somatic
%%metro file: ft_out | VCF | Annotated
%%metro file: pon_out | VCF | PoN filtered
%%metro file: msi_out | MSI | Instability
%%metro files: cnv_out | TSV | CNV / HRD
%%metro line: germline | Germline | #0570b0
%%metro line: tumour | Tumour | #d94801

graph LR
    subgraph input_sec [Inputs]
        pairs_in[ ]
        convert_g[CRAM -> BAM\ngermline]
        convert_t[CRAM -> BAM\ntumour]

        pairs_in -->|germline| convert_g
        pairs_in -->|tumour| convert_t
    end

    subgraph somatic_sec [Somatic calling]
        tnhap[Sentieon\nTNhaplotyper2]
        tnhapfilter[TNhapfilter]
        funcotator[GATK\nFuncotator]
        pon[Panel of\nnormals]
        somatic_out[ ]
        ft_out[ ]
        pon_out[ ]

        pairs_in -->|germline| tnhap
        pairs_in -->|tumour| tnhap
        tnhap -->|germline,tumour| tnhapfilter
        tnhapfilter -->|germline,tumour| somatic_out
        tnhapfilter -->|germline,tumour| funcotator
        funcotator -->|germline,tumour| ft_out
        funcotator -->|germline,tumour| pon
        pon -->|germline,tumour| pon_out
    end

    subgraph msi_sec [MSI]
        msisensor[msisensor2]
        msi_out[ ]

        convert_g -->|germline| msisensor
        convert_t -->|tumour| msisensor
        msisensor -->|germline,tumour| msi_out
    end

    subgraph cnv_sec [Copy number / HRD]
        split_g[Region split\ngermline]
        split_t[Region split\ntumour]
        bam2seqz[Sequenza\nbam2seqz]
        seqz[Sequenza\nseqz merge]
        fit[Sequenza fit\n+ scarHRD]
        adjust[CNV value\nadjust]
        cnv_out[ ]

        convert_g -->|germline| split_g
        convert_t -->|tumour| split_t
        split_g -->|germline| bam2seqz
        split_t -->|tumour| bam2seqz
        bam2seqz -->|germline,tumour| seqz
        seqz -->|germline,tumour| fit
        fit -->|germline,tumour| adjust
        adjust -->|germline,tumour| cnv_out
    end
